permissions:
  contents: write
  pages: write

name: Calculadora Pombo

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 

      - name: Load SiteKEY
        run: |
          find . -type f -name "*.html" -exec sed -i "s/{{site_key}}/${{ secrets.SITEKEY }}/g" {} \;

      - name: Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper 'cache --timeout=3600'

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: .  